const ADD_PATIENT = 'ADD_PATIENT';
const ADD_TREATMENT = 'ADD_TREATMENT';
const ADD_NAME = 'ADD_NAME';

const ADD_PATIENT_HISTORY = 'ADD_PATIENT_HISTORY';
export { ADD_PATIENT, ADD_PATIENT_HISTORY, ADD_TREATMENT, ADD_NAME };
