const ADD_PATIENT = 'ADD_PATIENT';
const ADD_NOTE = 'ADD_NOTE';
const ADD_TREATMENT = 'ADD_TREATMENT';
const ADD_NAME = 'ADD_NAME';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const LOGOUT = 'LOGOUT';

export { ADD_PATIENT, ADD_NOTE, ADD_TREATMENT, ADD_NAME, LOGIN, SIGNUP, LOGOUT };
